// Mock data for سرد رقمي platform

export const currentUser = {
  id: '1',
  name: 'أحمد محمد الزهراني',
  username: 'ahmed.zahrani',
  avatar: '',
  bio: 'مهندس برمجيات | شغوف بالتقنية والمجتمع | متطوع نشط',
  location: 'الرياض، المملكة العربية السعودية',
  followers: 0,
  following: 0,
  activities: 2,
  courses: 1,
  joinDate: '2024-09-01',
  verified: false,
  role: 'individual' as const,
};

export const currentOrg = {
  id: 'org1',
  name: 'منظمة رواد التطوع',
  username: 'rwad.volunteer',
  avatar: '',
  cover: '',
  bio: 'منظمة تطوعية تهتم بتنمية المجتمع وتمكين الشباب من خلال برامج التدريب والأنشطة المجتمعية',
  category: 'تطوع ومجتمع',
  location: 'الرياض، المملكة العربية السعودية',
  followers: 0,
  activities: 5,
  courses: 3,
  members: 3,
  verified: true,
  role: 'org' as const,
};

export const users = [
  { id: '1', name: 'أحمد محمد الزهراني', username: 'ahmed.zahrani', avatar: '', bio: 'مهندس برمجيات', location: 'الرياض', followers: 0, following: 0, verified: false, status: 'active', joinDate: '2024-09-01', role: 'individual' },
  { id: '2', name: 'سارة عبدالله الأحمد', username: 'sara.ahmad', avatar: '', bio: 'معلمة ومدربة', location: 'جدة', followers: 0, following: 0, verified: false, status: 'active', joinDate: '2024-07-15', role: 'individual' },
  { id: '3', name: 'محمد عمر الفيصل', username: 'mohd.faisal', avatar: '', bio: 'رائد أعمال', location: 'الدمام', followers: 0, following: 0, verified: true, status: 'active', joinDate: '2024-12-01', role: 'individual' },
  { id: '4', name: 'نورة سعد الربيعي', username: 'noura.rabiee', avatar: '', bio: 'مصممة جرافيك', location: 'الرياض', followers: 0, following: 0, verified: false, status: 'active', joinDate: '2024-01-10', role: 'individual' },
  { id: '5', name: 'فهد خالد المطيري', username: 'fahad.mutairi', avatar: '', bio: 'طالب دكتوراه', location: 'الرياض', followers: 0, following: 0, verified: false, status: 'suspended', joinDate: '2024-11-20', role: 'individual' },
  { id: '6', name: 'هند راشد القحطاني', username: 'hend.qahtani', avatar: '', bio: 'محامية', location: 'جدة', followers: 0, following: 0, verified: false, status: 'active', joinDate: '2024-05-08', role: 'individual' },
];

export const organizations = [
  { id: 'org1', name: 'منظمة رواد التطوع', username: 'rwad', category: 'تطوع', location: 'الرياض', followers: 0, verified: true, status: 'active', joinDate: '2024-01-01', activities: 5, courses: 3 },
  { id: 'org2', name: 'أكاديمية المستقبل', username: 'future.academy', category: 'تعليم', location: 'جدة', followers: 0, verified: true, status: 'active', joinDate: '2024-06-10', activities: 4, courses: 4 },
  { id: 'org3', name: 'مركز الابتكار التقني', username: 'tech.innovate', category: 'تقنية', location: 'الدمام', followers: 0, verified: false, status: 'pending', joinDate: '2024-02-14', activities: 2, courses: 2 },
  { id: 'org4', name: 'جمعية البيئة والطبيعة', username: 'eco.saudi', category: 'بيئة', location: 'تبوك', followers: 0, verified: true, status: 'active', joinDate: '2024-09-01', activities: 3, courses: 1 },
  { id: 'org5', name: 'نادي ريادة الأعمال', username: 'startup.club', category: 'ريادة أعمال', location: 'الرياض', followers: 0, verified: false, status: 'pending', joinDate: '2024-01-05', activities: 2, courses: 2 },
];

export const posts = [
  {
    id: 'p1',
    author: { id: '2', name: 'سارة عبدالله الأحمد', avatar: '', username: 'sara.ahmad' },
    content: 'انتهيت للتو من دورة تدريبية رائعة في مجال تطوير الذات، الشكر الجزيل لجميع المدربين والمشاركين على هذه التجربة الملهمة. أتطلع إلى تطبيق ما تعلمته في حياتي العملية والمهنية. 🎯✨',
    image: '',
    likes: 0,
    comments: 0,
    shares: 0,
    time: 'منذ ساعتين',
    liked: false,
    org: null,
  },
  {
    id: 'p2',
    author: { id: 'org1', name: 'منظمة رواد التطوع', avatar: '', username: 'rwad' },
    content: 'يسعدنا الإعلان عن انطلاق برنامج "صناع التغيير" للعام 2025، وهو برنامج تدريبي مكثف لمدة 3 أشهر يستهدف الشباب الراغبين في خدمة مجتمعاتهم وتطوير مهاراتهم القيادية والتطوعية. سارعوا بالتسجيل!',
    image: '',
    likes: 0,
    comments: 0,
    shares: 0,
    time: 'منذ 4 ساعات',
    liked: false,
    org: 'org',
  },
  {
    id: 'p3',
    author: { id: '3', name: 'محمد عمر الفيصل', avatar: '', username: 'mohd.faisal' },
    content: 'فكرة اليوم: المجتمعات القوية لا تُبنى بالحوافز المادية فقط، بل بالروابط الإنسانية والقيم المشتركة. كيف يمكننا بناء مجتمعات رقمية أكثر إنسانية وتعاوناً؟ شاركوني أفكاركم! 💭',
    image: '',
    likes: 0,
    comments: 0,
    shares: 0,
    time: 'منذ 6 ساعات',
    liked: false,
    org: null,
  },
  {
    id: 'p4',
    author: { id: 'org2', name: 'أكاديمية المستقبل', avatar: '', username: 'future.academy' },
    content: 'بالتعاون مع أبرز خبراء التعليم التقني في المنطقة، نطلق سلسلة جديدة من الدورات المجانية في: البرمجة، الذكاء الاصطناعي، والتصميم الرقمي. سجّل الآن قبل امتلاء الأماكن!',
    image: '',
    likes: 0,
    comments: 0,
    shares: 0,
    time: 'أمس',
    liked: false,
    org: 'org',
  },
  {
    id: 'p5',
    author: { id: '1', name: 'أحمد محمد الزهراني', avatar: '', username: 'ahmed.zahrani' },
    content: 'شاركت اليوم في حملة تشجير في حديقة الملك عبدالله. تجربة جميلة ومليئة بالطاقة الإيجابية مع مجموعة رائعة من المتطوعين. كل شجرة نزرعها هي استثمار للأجيال القادمة 🌳💚',
    image: '',
    likes: 0,
    comments: 0,
    shares: 0,
    time: 'أمس',
    liked: false,
    org: null,
  },
];

export const activities = [
  {
    id: 'a1',
    title: 'ورشة القيادة المجتمعية',
    org: { id: 'org1', name: 'منظمة رواد التطوع', avatar: '' },
    category: 'تطوع',
    date: '2025-07-25',
    time: '10:00 ص',
    location: 'مركز الملك فهد الثقافي، الرياض',
    description: 'ورشة عمل تفاعلية تهدف إلى تطوير مهارات القيادة والعمل التطوعي لدى الشباب',
    seats: 50,
    registered: 0,
    price: 'مجاني',
    image: '',
    tags: ['قيادة', 'تطوع', 'شباب'],
  },
  {
    id: 'a2',
    title: 'هاكاثون الابتكار الاجتماعي',
    org: { id: 'org3', name: 'مركز الابتكار التقني', avatar: '' },
    category: 'تقنية',
    date: '2025-08-01',
    time: '9:00 ص',
    location: 'حضوري وعن بعد',
    description: 'هاكاثون مدته 48 ساعة يجمع المبرمجين والمصممين وخبراء الأعمال لإيجاد حلول تقنية للتحديات الاجتماعية',
    seats: 120,
    registered: 0,
    price: 'مجاني',
    image: '',
    tags: ['هاكاثون', 'تقنية', 'ابتكار'],
  },
  {
    id: 'a3',
    title: 'يوم بيئي: نظّف وازرع',
    org: { id: 'org4', name: 'جمعية البيئة والطبيعة', avatar: '' },
    category: 'بيئة',
    date: '2025-07-30',
    time: '8:00 ص',
    location: 'حديقة الملك عبدالله، الرياض',
    description: 'نشاط بيئي جماعي لتنظيف الحدائق العامة وزراعة الأشجار في إطار احتفالات اليوم الوطني',
    seats: 200,
    registered: 0,
    price: 'مجاني',
    image: '',
    tags: ['بيئة', 'تشجير', 'تطوع'],
  },
  {
    id: 'a4',
    title: 'مؤتمر رواد الأعمال الشباب',
    org: { id: 'org5', name: 'نادي ريادة الأعمال', avatar: '' },
    category: 'ريادة أعمال',
    date: '2025-08-10',
    time: '2:00 م',
    location: 'فندق ماريوت، الرياض',
    description: 'مؤتمر سنوي يجمع نخبة من رواد الأعمال الشباب لتبادل الخبرات وعرض المشاريع الناشئة',
    seats: 300,
    registered: 0,
    price: '150 ريال',
    image: '',
    tags: ['ريادة', 'أعمال', 'شباب'],
  },
  {
    id: 'a5',
    title: 'دورة إسعافات أولية',
    org: { id: 'org1', name: 'منظمة رواد التطوع', avatar: '' },
    category: 'صحة',
    date: '2025-08-05',
    time: '6:00 م',
    location: 'مركز الصحة المجتمعية، جدة',
    description: 'دورة تدريبية معتمدة في الإسعافات الأولية والإنعاش القلبي الرئوي',
    seats: 30,
    registered: 0,
    price: 'مجاني',
    image: '',
    tags: ['صحة', 'إسعافات', 'تدريب'],
  },
];

export const courses = [
  {
    id: 'c1',
    title: 'مقدمة في البرمجة بلغة Python',
    org: { id: 'org2', name: 'أكاديمية المستقبل', avatar: '' },
    category: 'برمجة',
    level: 'مبتدئ',
    duration: '8 أسابيع',
    lectures: 24,
    students: 0,
    rating: 0,
    price: 'مجاني',
    image: '',
    description: 'تعلم أساسيات البرمجة بلغة Python من الصفر حتى الاحتراف مع تطبيقات عملية',
    tags: ['Python', 'برمجة', 'مبتدئ'],
    enrolled: false,
    progress: 0,
  },
  {
    id: 'c2',
    title: 'أساسيات الذكاء الاصطناعي',
    org: { id: 'org2', name: 'أكاديمية المستقبل', avatar: '' },
    category: 'تقنية',
    level: 'متوسط',
    duration: '12 أسبوعاً',
    lectures: 36,
    students: 0,
    rating: 0,
    price: '299 ريال',
    image: '',
    description: 'استكشف عالم الذكاء الاصطناعي وتعلم بناء نماذج تعلم الآلة بطريقة عملية',
    tags: ['AI', 'ML', 'تقنية'],
    enrolled: false,
    progress: 0,
  },
  {
    id: 'c3',
    title: 'مهارات القيادة والتأثير',
    org: { id: 'org1', name: 'منظمة رواد التطوع', avatar: '' },
    category: 'تطوير ذاتي',
    level: 'جميع المستويات',
    duration: '6 أسابيع',
    lectures: 18,
    students: 0,
    rating: 0,
    price: 'مجاني',
    image: '',
    description: 'طوّر مهاراتك القيادية وتعلم فن التأثير وبناء الفرق الفعّالة',
    tags: ['قيادة', 'تأثير', 'فريق'],
    enrolled: false,
    progress: 0,
  },
  {
    id: 'c4',
    title: 'تصميم تجربة المستخدم UX',
    org: { id: 'org3', name: 'مركز الابتكار التقني', avatar: '' },
    category: 'تصميم',
    level: 'متوسط',
    duration: '10 أسابيع',
    lectures: 30,
    students: 0,
    rating: 0,
    price: '199 ريال',
    image: '',
    description: 'احترف تصميم تجربة المستخدم وإنشاء واجهات سهلة الاستخدام وجذابة',
    tags: ['UX', 'تصميم', 'واجهات'],
    enrolled: false,
    progress: 0,
  },
  {
    id: 'c5',
    title: 'ريادة الأعمال من الصفر',
    org: { id: 'org5', name: 'نادي ريادة الأعمال', avatar: '' },
    category: 'ريادة أعمال',
    level: 'مبتدئ',
    duration: '8 أسابيع',
    lectures: 22,
    students: 0,
    rating: 0,
    price: '149 ريال',
    image: '',
    description: 'تعلم كيف تبدأ مشروعك الخاص من الفكرة حتى التنفيذ والنجاح',
    tags: ['ريادة', 'أعمال', 'مشاريع'],
    enrolled: false,
    progress: 0,
  },
];

export const groups = [
  {
    id: 'g1',
    name: 'مطورو البرمجيات العرب',
    description: 'مجتمع المطورين العرب لتبادل الخبرات والمعرفة التقنية',
    members: 1,
    category: 'تقنية',
    privacy: 'عام',
    image: '',
    joined: true,
    posts: 0,
  },
  {
    id: 'g2',
    name: 'رواد التطوع - الرياض',
    description: 'مجموعة للمتطوعين في مدينة الرياض لتنسيق الأنشطة والفعاليات',
    members: 1,
    category: 'تطوع',
    privacy: 'عام',
    image: '',
    joined: true,
    posts: 0,
  },
  {
    id: 'g3',
    name: 'شبكة رواد الأعمال الشباب',
    description: 'منصة تواصل لرواد الأعمال الشباب لتبادل الأفكار والشراكات',
    members: 1,
    category: 'ريادة أعمال',
    privacy: 'عام',
    image: '',
    joined: false,
    posts: 0,
  },
  {
    id: 'g4',
    name: 'عشاق التصميم الجرافيكي',
    description: 'مجتمع المصممين العرب لمشاركة الأعمال والنقاش حول التصميم',
    members: 1,
    category: 'تصميم',
    privacy: 'عام',
    image: '',
    joined: false,
    posts: 0,
  },
  {
    id: 'g5',
    name: 'محبو الكتاب العربي',
    description: 'مجموعة للمهتمين بالقراءة ومناقشة الكتب العربية',
    members: 1,
    category: 'ثقافة',
    privacy: 'خاص',
    image: '',
    joined: true,
    posts: 0,
  },
];

export const notifications = [
  { id: 'n1', type: 'like', user: { name: 'سارة الأحمد', avatar: '' }, content: 'أعجبت بمنشورك', time: 'منذ 5 دقائق', read: false },
  { id: 'n2', type: 'comment', user: { name: 'محمد الفيصل', avatar: '' }, content: 'علّق على منشورك: "فكرة رائعة جداً!"', time: 'منذ 20 دقيقة', read: false },
  { id: 'n3', type: 'follow', user: { name: 'نورة الربيعي', avatar: '' }, content: 'بدأت بمتابعتك', time: 'منذ ساعة', read: false },
  { id: 'n4', type: 'activity', user: { name: 'منظمة رواد التطوع', avatar: '' }, content: 'تم تسجيلك في نشاط "ورشة القيادة المجتمعية"', time: 'منذ 3 ساعات', read: true },
  { id: 'n5', type: 'course', user: { name: 'أكاديمية المستقبل', avatar: '' }, content: 'تمت إضافة درس جديد في دورة Python', time: 'منذ 5 ساعات', read: true },
  { id: 'n6', type: 'system', user: { name: 'سرد رقمي', avatar: '' }, content: 'مرحباً بك في المنصة! ابدأ باستكشاف الأنشطة والمجموعات', time: 'منذ يومين', read: true },
];

export const conversations = [
  {
    id: 'conv1',
    user: { id: '2', name: 'سارة الأحمد', avatar: '', online: true },
    lastMessage: 'شكراً جزيلاً على المساعدة! 🙏',
    time: 'منذ 10 دقائق',
    unread: 2,
    messages: [
      { id: 'm1', sender: 'me', content: 'أهلاً سارة، كيف يمكنني مساعدتك؟', time: '10:30 ص' },
      { id: 'm2', sender: 'other', content: 'مرحباً أحمد! أريد الاستفسار عن ورشة العمل القادمة', time: '10:32 ص' },
      { id: 'm3', sender: 'me', content: 'بالطبع، الورشة ستكون يوم الجمعة الساعة 10 صباحاً في مركز الملك فهد الثقافي', time: '10:35 ص' },
      { id: 'm4', sender: 'other', content: 'ممتاز! هل يلزم التسجيل المسبق؟', time: '10:36 ص' },
      { id: 'm5', sender: 'me', content: 'نعم يرجى التسجيل عبر المنصة، الأماكن محدودة', time: '10:37 ص' },
      { id: 'm6', sender: 'other', content: 'شكراً جزيلاً على المساعدة! 🙏', time: '10:38 ص' },
    ],
  },
  {
    id: 'conv2',
    user: { id: '3', name: 'محمد الفيصل', avatar: '', online: false },
    lastMessage: 'متى موعد اجتماع الفريق؟',
    time: 'أمس',
    unread: 0,
    messages: [
      { id: 'm1', sender: 'other', content: 'متى موعد اجتماع الفريق؟', time: 'أمس' },
    ],
  },
  {
    id: 'conv3',
    user: { id: 'org1', name: 'منظمة رواد التطوع', avatar: '', online: true },
    lastMessage: 'نشكرك على انضمامك إلى الفعالية',
    time: 'منذ يومين',
    unread: 0,
    messages: [
      { id: 'm1', sender: 'other', content: 'نشكرك على انضمامك إلى الفعالية', time: 'منذ يومين' },
    ],
  },
];

export const adminStats = {
  totalUsers: 5,
  totalOrgs: 1,
  totalPosts: 4,
  totalActivities: 5,
  totalCourses: 5,
  pendingOrgs: 0,
  reportedPosts: 0,
  activeUsers: 5,
};

export const systemLogs = [
  { id: 'l1', type: 'info', message: 'مستخدم جديد: ahmed.zahrani@email.com', time: '2025-07-13 14:32:11', ip: '192.168.1.1' },
  { id: 'l2', type: 'warning', message: 'محاولات تسجيل دخول فاشلة متعددة للحساب: test@email.com', time: '2025-07-13 14:28:45', ip: '10.0.0.5' },
  { id: 'l3', type: 'error', message: 'فشل إرسال البريد الإلكتروني لـ: noura@email.com', time: '2025-07-13 14:15:30', ip: '-' },
  { id: 'l4', type: 'info', message: 'تم تحديث إعدادات المنصة بواسطة المشرف', time: '2025-07-13 13:45:00', ip: '192.168.1.100' },
  { id: 'l5', type: 'info', message: 'تم قبول منظمة: أكاديمية التقنية', time: '2025-07-13 12:30:22', ip: '192.168.1.100' },
  { id: 'l6', type: 'warning', message: 'منشور مبلّغ عنه: ID #2847 - محتوى مخالف', time: '2025-07-13 11:20:15', ip: '-' },
  { id: 'l7', type: 'info', message: 'تم إنشاء نسخة احتياطية يومية للقاعدة البيانات', time: '2025-07-13 03:00:00', ip: '-' },
  { id: 'l8', type: 'error', message: 'خطأ في اتصال قاعدة البيانات - تمت استعادة الاتصال', time: '2025-07-12 22:14:30', ip: '-' },
];

export const orgAnalyticsData = {
  followerGrowth: [
    { month: 'يناير', followers: 0 },
    { month: 'فبراير', followers: 0 },
    { month: 'مارس', followers: 0 },
    { month: 'أبريل', followers: 0 },
    { month: 'مايو', followers: 0 },
    { month: 'يونيو', followers: 0 },
    { month: 'يوليو', followers: 0 },
  ],
  activityParticipation: [
    { activity: 'ورشة القيادة', participants: 0 },
    { activity: 'يوم التطوع', participants: 0 },
    { activity: 'دورة الإسعافات', participants: 0 },
    { activity: 'محاضرة التمكين', participants: 0 },
    { activity: 'رحلة الأنشطة', participants: 0 },
  ],
  engagementByType: [
    { type: 'إعجابات', value: 0 },
    { type: 'تعليقات', value: 0 },
    { type: 'مشاركات', value: 0 },
    { type: 'حفظ', value: 0 },
  ],
};

export const adminAnalyticsData = {
  userGrowth: [
    { month: 'يناير', users: 0 },
    { month: 'فبراير', users: 0 },
    { month: 'مارس', users: 0 },
    { month: 'أبريل', users: 0 },
    { month: 'مايو', users: 0 },
    { month: 'يونيو', users: 0 },
    { month: 'يوليو', users: 5 },
  ],
  contentByType: [
    { type: 'منشورات', value: 4 },
    { type: 'أنشطة', value: 5 },
    { type: 'دورات', value: 5 },
    { type: 'مجموعات', value: 5 },
  ],
  reportsByStatus: [
    { status: 'تحت المراجعة', value: 0 },
    { status: 'تمت المعالجة', value: 0 },
    { status: 'مرفوضة', value: 0 },
  ],
};
